cluster:
  name: {{ .CLUSTER_NAME }}
  version: 1.16
  rolearn: {{ .ROLE_ARN }}
  resourcesvpcconfig:
    endpointpublicaccess: true
    subnetids:
      {{ range $subnetId := split .SUBNET_IDS .SEPARATOR }}
      - {{ $subnetId }}
      {{ end }}
nodegroups:
  - nodegroupname: {{ .CLUSTER_NAME }}
    noderole: {{ .NODE_ROLE }}
    disksize: 100
    subnets:
      {{ range $subnetId := split .SUBNET_IDS .SEPARATOR }}
      - {{ $subnetId }}
      {{ end }}
    instancetypes:
      - r6g.xlarge
    scalingconfig:
      desiredsize: 1
      maxsize: 1
      minsize: 1
    labels:
      node-name: funcbench-{{ .PR_NUMBER }}
