go:
    # Whenever the Go version is updated here, .travis.yml and
    # .circle/config.yml should also be updated if in use.
    version: 1.12
repository:
    path: github.com/prometheus/prombench
build:
    binaries:
        - name: prombench
          path: ./cmd/prombench
        - name: scaler
          path: ./tools/scaler
        - name: fake-webserver
          path: ./tools/fake-webserver
        - name: commentMonitor
          path: tools/commentMonitor
        - name: amGithubNotifier
          path: tools/amGithubNotifier
    flags: -a -tags netgo

crossbuild:
    platforms:
        - linux/amd64
