---
apiVersion: v1
kind: Namespace
metadata:
  name: prombench-{{ environ('PR_NUMBER') }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: loadgen-scaler
  namespace: prombench-{{ environ('PR_NUMBER') }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: loadgen-scaler
  namespace: prombench-{{ environ('PR_NUMBER') }}
rules:
- apiGroups:
  - extensions
  resources:
  - deployments
  verbs: ["get", "update"]
---
#need to give update access to loadgen-scaler
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: loadgen-scaler
  namespace: prombench-{{ environ('PR_NUMBER') }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: loadgen-scaler
subjects:
- kind: ServiceAccount
  name: loadgen-scaler
  namespace: prombench-{{ environ('PR_NUMBER') }}
---
#Prometheus RBAC
apiVersion: v1
kind: ServiceAccount
metadata:
  name: prometheus
  namespace: prombench-{{ environ('PR_NUMBER') }}
---
#Not made during cluster creation time to create with specific service-account  
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: prometheus-{{ environ('PR_NUMBER') }}
rules:
- apiGroups: [""]
  resources:
  - nodes
  - nodes/proxy
  - services
  - endpoints
  - pods
  verbs: ["get", "list", "watch"]
- apiGroups:
  - extensions
  resources:
  - ingresses
  verbs: ["get", "list", "watch"]
- nonResourceURLs: ["/metrics"]
  verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: prometheus
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: prometheus-{{ environ('PR_NUMBER') }}
subjects:
- kind: ServiceAccount
  name: prometheus
  namespace: prombench-{{ environ('PR_NUMBER') }}