zone: us-east1-b
cluster:
  name: {{ environ('CLUSTER_NAME') }}
  addonsconfig:
    kubernetesdashboard: 
      disabled: false
#  initialclusterversion: 1.9.6-gke.0
  nodepools:
  - name: prometheus
    initialnodecount: {{ ( prometheus.instances | length ) + 1 }}
    config:
      machinetype: {{ prometheus.machineType }}
      imagetype: COS
      disksizegb: {{ prometheus.disksizegb }}
      localssdcount: {{ prometheus.localssdcount }}
      labels:
        isolation: prometheus
  - name: nodes
    initialnodecount: {{ workers.nodecount }}
    config:
      machinetype: {{ workers.machineType }}
      imagetype: COS
      disksizegb: {{ workers.disksizegb }}
      localssdcount: {{ workers.localssdcount }}
      labels:
        isolation: none