apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: kube-state-metrics
  namespace: prombench-{{ environ('PR_NUMBER') }}
spec:
  replicas: 1
  template:
    metadata:
      namespace: prombench-{{ environ('PR_NUMBER') }}
      labels:
        app: kube-state-metrics
    spec:
      containers:
      - name: kube-state-metrics
        image: gcr.io/google_containers/kube-state-metrics:v0.3.0
        ports:
        - name: metrics
          containerPort: 8080
      nodeSelector:
        cloud.google.com/gke-nodepool: nodes-{{ environ('PR_NUMBER') }}
        isolation: none
---
apiVersion: v1
kind: Service
metadata:
  name: kube-state-metrics
  namespace: prombench-{{ environ('PR_NUMBER') }}
  labels:
    app: kube-state-metrics
    monitored: "true"
spec:
  ports:
  - name: metrics
    port: 8080
    targetPort: metrics
    protocol: TCP
  selector:
    app: kube-state-metrics
