apiVersion: v1
kind: ServiceAccount
metadata:
  name: loadgen-scaler
  namespace: "{{ .PR_NUMBER }}"
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: prometheus
  namespace: "{{ .PR_NUMBER }}"