apiVersion: batch/v1
kind: Job
metadata:
  name: funcbench-test-{{ .PR_NUMBER }}
  namespace: funcbench-{{ .PR_NUMBER }}
spec:
  # never re-create a new pod
  backoffLimit: 0
  template:
    spec:
      restartPolicy: Never
      containers:
      - name: funcbench
        image: docker.io/nevill/funcbench:20200324
        imagePullPolicy: Always
        args:
          - "--verbose"
          - "--owner"
          - "{{ .GITHUB_ORG }}"
          - "--repo"
          - "{{ .GITHUB_REPO }}"
          - "--github-pr"
          - "{{ .PR_NUMBER }}"
          - "--workspace"
          - "/build"
          - "{{ .BRANCH }}"
          - "{{ .REGEX }}"
        env:
          - name: GITHUB_TOKEN
            value: "{{ .GITHUB_TOKEN }}"
          - name: GITHUB_SHA
            value: "{{ .LAST_COMMIT_SHA }}"
      nodeSelector:
        cloud.google.com/gke-nodepool: funcbench-{{ .PR_NUMBER }}
        isolation: prometheus
