apiVersion: batch/v1
kind: Job
metadata:
  name: funcbench-test-{{ .PR_NUMBER }}
  namespace: funcbench-{{ .PR_NUMBER }}
spec:
  # never re-create a new pod
  backoffLimit: 0
  template:
    spec:
      restartPolicy: Never
      initContainers:
      - name: clean-up
        image: busybox:latest
        command: ['sh', '-c', 'rm -fr /build/* && mkdir /build/tmp && mkdir /build/src']
        volumeMounts:
        - name: instance-ssd
          mountPath: /build
      containers:
      - name: funcbench
        image: nevill/funcbench:latest
        imagePullPolicy: Always
        args:
          - "-o"
          - "{{ .GITHUB_ORG }}"
          - "-r"
          - "{{ .GITHUB_REPO }}"
          - "-p"
          - "{{ .PR_NUMBER }}"
          - "{{ .BRANCH }}"
          - "{{ .REGEX }}"
        env:
          - name: GITHUB_WORKSPACE
            value: /build/src
          - name: GITHUB_TOKEN
            value: "{{ .GITHUB_TOKEN }}"
          - name: GITHUB_SHA
            value: "{{ .LAST_COMMIT_SHA }}"
        volumeMounts:
        - name: instance-ssd
          mountPath: /build
      volumes:
      - name: instance-ssd
        hostPath:
          # /mnt is where GKE keeps it's SSD
          # don't change this if you want Prometheus to take advantage of these local SSDs
          path: /mnt/disks/ssd0
      nodeSelector:
        cloud.google.com/gke-nodepool: funcbench-{{ .PR_NUMBER }}
        isolation: prometheus
