zone: {{ environ('ZONE') }}
cluster:
  name: {{ environ('CLUSTER_NAME') }}
  initialclusterversion: 1.10.2-gke.3
  nodepools:
  {%- for p in prometheus.instances %}
  - name: prometheus-test-{{ environ(p.name) }}
    initialnodecount: 1
    config:
      machinetype: n1-standard-1
      imagetype: COS
      disksizegb: 100
      localssdcount: 1
      labels:
        isolation: prometheus-test-{{ environ(p.name) }}
  {%- endfor %}
  - name: prometheus-meta
    initialnodecount: 1
    config:
      machinetype: n1-standard-1
      imagetype: COS
      disksizegb: 100
      localssdcount: 1
      labels:
        isolation: prometheus-meta
  - name: nodes
    initialnodecount: {{ workers.nodecount }}
    config:
      machinetype: n1-standard-2
      imagetype: COS
      disksizegb: 100
      localssdcount: 0
      labels:
        isolation: none