zone: us-east1-b
cluster:
  name: {{ environ('CLUSTER_NAME') }}
  initialclusterversion: 1.10.2-gke.3
  nodepools:
  {%- for p in prometheus.instances %}
  - name: prometheus-test-{{ environ(p.name) }}
    initialnodecount: 1
    config:
      machinetype: {{ prometheus.machineType }}
      imagetype: COS
      disksizegb: {{ prometheus.disksizegb }}
      localssdcount: {{ prometheus.localssdcount }}
      labels:
        isolation: prometheus-test-{{ environ(p.name) }}
  {%- endfor %}
  - name: prometheus-meta
    initialnodecount: 1
    config:
      machinetype: {{ prometheus.machineType }}
      imagetype: COS
      disksizegb: {{ prometheus.disksizegb }}
      localssdcount: {{ prometheus.localssdcount }}
      labels:
        isolation: prometheus-meta
  - name: nodes
    initialnodecount: {{ workers.nodecount }}
    config:
      machinetype: {{ workers.machineType }}
      imagetype: COS
      disksizegb: {{ workers.disksizegb }}
      localssdcount: {{ workers.localssdcount }}
      labels:
        isolation: none