apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  name: nodes
spec:
  associatePublicIp: true
  machineType: {{ workers.machineType }}
  maxSize: {{ workers.count }}
  minSize: {{ workers.count }}
  nodeLabels:
    isolation: none
  role: Node
  zones:
  - {{ awsRegion }}a
