plank:
  job_url_template: 'http://35.227.204.14/log?job={{.Spec.Job}}&id={{.Status.BuildID}}'
  pod_pending_timeout: 60m
  default_decoration_config:
    timeout: 7200000000000 # 2h
    grace_period: 15000000000 # 15s
    utility_images:
      clonerefs: "registry.svc.ci.openshift.org/ci/clonerefs:latest"
      initupload: "registry.svc.ci.openshift.org/ci/initupload:latest"
      entrypoint: "registry.svc.ci.openshift.org/ci/entrypoint:latest"
      sidecar: "registry.svc.ci.openshift.org/ci/sidecar:latest"
    gcs_configuration:
      bucket: "prometheus-prow"
      path_strategy: "explicit"
      default_org: "sipian"
      default_repo: "prometheus"
    gcs_credentials_secret: "service-account"

log_level: debug

periodics:
- interval: 10m
  agent: kubernetes
  name: echo-test
  spec:
    containers:
    - image: alpine:latest
      command: ["/bin/date"]

# These configurations are NOT for PR presubmits as used by the trigger plugin. 
# These are used to create prowjobs for the benchmark plugin. 
presubmits:
  sipian/prometheus:
  - name: build-PR-images
    context: build-PR-images
    always_run: false
    skip_report: false
    agent: kubernetes
    decorate: true
    path_alias: /github.com/prometheus/prometheus
    spec:
      containers:
      - image: sipian/golang-builder:prow
        imagePullPolicy: Always
        command:
        - "./prow/benchmark_build.sh"
        volumeMounts:
        - name: serviceaccount
          mountPath: /etc/serviceaccount
          readOnly: true
        - name: docker-sock
          mountPath: /var/run/docker.sock
      volumes:
      - name: serviceaccount
        secret:
          secretName: service-account          
      - name: docker-sock 
        hostPath: 
            path: /var/run/docker.sock

  sipian/prometheus:
  - name: start-benchmark
    context: start-benchmark
    always_run: false
    skip_report: false
    agent: kubernetes
    spec:
      containers:
      - image: gcr.io/prometheus-test-204522/prombench:v0.1.0
        imagePullPolicy: Always
        command:
        - "make deploy"
        env:
        - name: ZONE
          value: us-east1-b
        - name: CLUSTER_NAME
          value: prombench
        volumeMounts:
        - name: serviceaccount
          mountPath: /etc/serviceaccount/
          readOnly: true
      volumes:
      - name: serviceaccount
        secret:
          secretName: service-account

  sipian/prometheus:
  - name: cancel-benchmark
    context: cancel-benchmark
    always_run: false
    skip_report: false
    agent: kubernetes
    spec:
      containers:
      - image: gcr.io/prometheus-test-204522/prombench:v0.1.0
        imagePullPolicy: Always
        command:
        - "make clean"
        env:
        - name: ZONE
          value: us-east1-b
        - name: CLUSTER_NAME
          value: prombench
        volumeMounts:
        - name: serviceaccount
          mountPath: /etc/serviceaccount/
          readOnly: true
      volumes:
      - name: serviceaccount
        secret:
          secretName: service-account