zone: {{ .ZONE }}
projectid: {{ .PROJECT_ID }}
cluster:
  name: {{ .CLUSTER_NAME }}
  nodepools:
  # These node-pools will be deployed on triggering benchmark
  - name: funcbench-{{ .PR_NUMBER }}
    initialnodecount: 1
    config:
      machinetype: n1-highmem-4
      imagetype: COS
      disksizegb: 100
      labels:
        isolation: funcbench
