  projectid: prometheus-188100
  zone: europe-west1-b
  cluster:
    name: prombench
    addonsconfig:
      kubernetesdashboard: 
        disabled: false
    initialclusterversion: 1.9.6-gke.0
    nodepools:
    - initialnodecount: 1
      <<: &label
        name: prometheus-stable
      config:
        machinetype: n1-standard-1
        imagetype: COS
        disksizegb: 100
        localssdcount: 1
        labels:
          <<: *label
    - initialnodecount: 1
      <<: &label
        name: prometheus-test
      config:
        machinetype: n1-standard-1
        imagetype: COS
        disksizegb: 100
        localssdcount: 1
        labels:
          <<: *label
    - initialnodecount: 1
      <<: &label
        name: load-collector
      config:
        machinetype: n1-standard-1
        imagetype: COS
        disksizegb: 100
        localssdcount: 1
        labels:
          <<: *label